name: ChangelogBook
version: '${version}'
main: com.puffmc.changelog.ChangelogPlugin
api-version: '1.21'
authors: [Bishyy]
description: Plugin displaying changelog to players with multi-language support
commands:
  changelog:
    description: Display changelog help and commands
    usage: /changelog
    aliases: [cl]
    permission: changelogbook.use
permissions:
  changelogbook.use:
    description: Allows access to changelog
    default: true
  changelogbook.admin:
    description: Allows access to changelog administration
    default: op
  changelogbook.update.notify:
    description: Receive plugin update notifications
    default: op