/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    java
    application
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

group = "com.puffmc"
version = "1.4.0"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    // Spigot API repository
    maven("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    // Paper API repository
    maven("https://repo.papermc.io/repository/maven-public/")
}

dependencies {
    // Spigot API - supports 1.8 to 1.21.11
    compileOnly("org.spigotmc:spigot-api:1.21.1-R0.1-SNAPSHOT")
    
    // Gson - available in Spigot/Paper runtime
    compileOnly("com.google.code.gson:gson:2.10.1")
    
    // MySQL connector
    implementation("mysql:mysql-connector-java:8.0.33")
    
    // HikariCP for database connection pooling
    implementation("com.zaxxer:HikariCP:5.1.0")
    
    // Guava - already included in Paper/Spigot
    compileOnly("com.google.guava:guava:33.3.1-jre")
    
    // JUnit for testing
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.1")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.puffmc.changelog.ChangelogPlugin"
}

tasks {
    jar {
        enabled = false
    }
    
    shadowJar {
        archiveBaseName.set("changelogbook")
        archiveClassifier.set("")
        archiveVersion.set("")
        destinationDirectory.set(layout.buildDirectory.dir("libs"))
        
        // Minimize JAR size
        minimize()
        
        relocate("com.mysql", "com.puffmc.changelog.libs.mysql")
        relocate("com.zaxxer.hikari", "com.puffmc.changelog.libs.hikari")
    }
    
    test {
        useJUnitPlatform()
    }
    
    processResources {
        val projectVersion = project.version.toString()
        filesMatching("plugin.yml") {
            expand("version" to projectVersion)
        }
    }
    
    build {
        dependsOn(shadowJar)
    }
}
